on: [pull_request]
permissions:
      checks: write
      contents: write
      pull-requests: write
      statuses: write


jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to get code
        uses: actions/checkout@v3
      - name: Run SAST scan
        run:
          npx snyk auth ${{ secrets.SNYK_API_KEY }}
          
          npx snyk code test --sarif-file-output=/home/runner/report.json ./
          
        shell: bash -l {0}
      - name: Run Mobb on the findings and get fixes
        if: failure()
        uses: mobb-dev/action@v1
        with:
          report-file: "/home/runner/report.json"
          api-key: ${{ secrets.MOBB_API_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
